### ISSUE TITLE
Fatal Error when type php artisan connexion:install

### ISSUE THREAD

**Issue by dukenst2006** [bishopm/connexion#1]
Hello @bishopm 
Congratulations for this great package !
I follow all your steps describe to install this package. But I founed this Error:
`C:\nginx\www\connexion
λ php artisan connexion:install
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Bishopm\Connexion\Providers\BaseServiceProvider' not found`

Any idea please to solve this Error
![screen](https://cloud.githubusercontent.com/assets/7965394/24088359/b4771ab0-0ce6-11e7-9444-8fb5b41c9d83.jpg)
?
Thanks ans Best regards !

**Comment by dukenst2006** [comment]
Hello @bishopm, 
I changed 'Bishopm\Connexion\Providers\BaseServiceProvider' to 
Bishopm\Connexion\Providers\ConnexionServiceProvider::class,
Now it's gave me this Error when i type : php artisan connexion:install

  [Illuminate\Database\QueryException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'connexion.settings' doesn't exist (SQL: select * from `s
  ettings`)

  [PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'connexion.settings' doesn't exist
Any idea?
Thanks !!

**Comment by bishopm** [comment]
Hi @dukenst2006 

Sorry you're having trouble with the package! I am still making working on it - it's pretty rough around the edges :)

You seem to have fixed the first problem which had to do with the renaming of the package from base to connexion. 

The second issue sounds like the migration hasn't run yet (or it ran previously and didn't complete - perhaps it crashed before creating the settings table?) Have a look at Console/InstallConnexionCommand and you can see all the setup stuff that is going on when that install command runs.

I haven't looked at that artisan command for a while. You may have more luck running it on a fresh install?

**Comment by bishopm** [comment]
Had another look at installing this on a fresh Laravel install and found a number of issues that have now been dealt with, included the two you flagged. Still a WIP though :)
